import type {Profile} from '@/types/profile';

const timestamp = '2026-06-30T06:00:00.000Z';

export const sampleProfiles: Profile[] = [
  {
    id: 'female-1',
    gender: 'female',
    status: 'active',
    isActivated: true,
    authorName: '김성수',
    starredByName: null,
    residence: '서울 강남구',
    birthYear: 1998,
    height: 164,
    job: 'IBK / 을지로 / 금융',
    religion: 'not_selected',
    mbti: 'ENFJ',
    hobbies: '독서, 러닝',
    smoking: 'non_smoker',
    drinking: 'drinker',
    idealType: '차분하고 대화가 잘 통하는 사람',
    matchmakerComment: '예의 있고 성실한 인상. 운동을 꾸준히 해요.',
    extra: '주말에는 전시 보러 가는 걸 좋아합니다.',
    adminMemo: '',
    photos: [
      {
        id: 'female-1-photo-1',
        url: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&w=900&q=80',
        alt: '프로필 사진 1',
        order: 0,
      },
      {
        id: 'female-1-photo-2',
        url: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&w=900&q=80',
        alt: '프로필 사진 2',
        order: 1,
      },
    ],
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: 'female-2',
    gender: 'female',
    status: 'blocked',
    isActivated: false,
    authorName: '이지은',
    starredByName: null,
    residence: '서울 송파구',
    birthYear: 1996,
    height: 168,
    job: '카카오 / 판교 / IT',
    religion: 'catholic',
    mbti: 'ISTP',
    hobbies: '요가, 여행',
    smoking: 'non_smoker',
    drinking: 'non_drinker',
    idealType: '자기 일에 책임감 있는 사람',
    matchmakerComment: '처음엔 조용하지만 친해지면 유쾌합니다.',
    extra: '',
    adminMemo: '',
    photos: [
      {
        id: 'female-2-photo-1',
        url: 'https://images.unsplash.com/photo-1502823403499-6ccfcf4fb453?auto=format&fit=crop&w=900&q=80',
        alt: '프로필 사진 1',
        order: 0,
      },
    ],
    createdAt: timestamp,
    updatedAt: timestamp,
  },
  {
    id: 'male-1',
    gender: 'male',
    status: 'active',
    isActivated: true,
    authorName: '박도윤',
    starredByName: null,
    residence: '서울 마포구',
    birthYear: 1994,
    height: 178,
    job: '네이버 / 분당 / IT',
    religion: 'christian',
    mbti: 'ENTJ',
    hobbies: '클라이밍, 와인',
    smoking: 'non_smoker',
    drinking: 'drinker',
    idealType: '밝고 독립적인 사람',
    matchmakerComment: '일정 조율 빠르고 매너가 좋습니다.',
    extra: '해외 근무 경험 있음',
    adminMemo: '',
    photos: [
      {
        id: 'male-1-photo-1',
        url: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&w=900&q=80',
        alt: '프로필 사진 1',
        order: 0,
      },
    ],
    createdAt: timestamp,
    updatedAt: timestamp,
  },
];
